services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  carro:
    build:
      context: .
      dockerfile: ./Carro/Dockerfile
    depends_on:
      - mosquitto

  servidor-feiradesantana:
    build:
      context: .
      dockerfile: ./Servidor/Dockerfile
    volumes:
      - ./utils/data:/data
    environment:
      - CIDADE=FeiraDeSantana
      - ARQUIVO_JSON=/data/FeiraDeSantana.json
    depends_on:
      - mosquitto

  servidor-salvador:
    build:
      context: .
      dockerfile: ./Servidor/Dockerfile
    volumes:
      - ./utils/data:/data
    environment:
      - CIDADE=Salvador
      - ARQUIVO_JSON=/data/Salvador.json
    depends_on:
      - mosquitto

  servidor-ilheus:
    build:
      context: .
      dockerfile: ./Servidor/Dockerfile
    volumes:
      - ./utils/data:/data
    environment:
      - CIDADE=Ilheus
      - ARQUIVO_JSON=/data/Ilheus.json
    depends_on:
      - mosquitto

