version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  carro:
    build: ./Carro
    depends_on:
      - mosquitto

  servidor:
    build: ./Servidor
    depends_on:
      - mosquitto
