services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  carro:
    build:
      context: .
      dockerfile: ./Carro/Dockerfile
    depends_on:
      - mosquitto

  servidor-bahia:
    build:
      context: .
      dockerfile: ./Servidor/Dockerfile
    volumes:
      - ./utils/data:/data
    ports:
      - "8080:8080"  # Mapeia a porta 8080 do container para a 8080 do host
    environment:
      - ESTADO=Bahia
      - ARQUIVO_JSON=/data/Bahia.json
    depends_on:
      - mosquitto
  
  servidor-minas:
    build:
      context: .
      dockerfile: ./Servidor/Dockerfile
    volumes:
      - ./utils/data:/data
    ports:
      - "8081:8080"  # Mapeia a porta 8080 do container para a 8080 do host
    environment:
      - ESTADO=MinasGerais
      - ARQUIVO_JSON=/data/MinasGerais.json
    depends_on:
      - mosquitto
  
  servidor-espiritosanto:
    build:
      context: .
      dockerfile: ./Servidor/Dockerfile
    volumes:
      - ./utils/data:/data
    ports:
      - "8082:8080"  # Mapeia a porta 8080 do container para a 8080 do host
    environment:
      - ESTADO=EspiritoSanto
      - ARQUIVO_JSON=/data/EspiritoSanto.json
    depends_on:
      - mosquitto
  