down:
	docker-compose down
up:
	clear
	docker-compose up --build -d
	docker-compose logs -f

logs:
	docker-compose logs -f

feira:
	clear
	docker-compose up --build -d servidor-feiradesantana
	docker-compose logs -f servidor-feiradesantana

ilheus:
	clear
	docker-compose up --build -d servidor-ilheus
	docker-compose logs -f servidor-ilheus

salvador:
	clear
	docker-compose up --build -d servidor-salvador
	docker-compose logs -f servidor-salvador