down:
	docker-compose down
up:
	clear
	docker-compose up --build -d
	docker-compose logs -f
carro:
	docker-compose run --rm carro
ilheus:
	clear
	docker-compose up --build -d servidor-ilheus
	docker-compose logs -f servidor-ilheus
salvador:
	clear
	docker-compose up --build -d servidor-salvador
	docker-compose logs -f servidor-salvador
feira:
	clear
	docker-compose up --build -d servidor-feiradesantana
	docker-compose logs -f servidor-feiradesantana